name: motar
networks:
  motar:
    driver: bridge
    ipam:
      config:
        - subnet: 10.11.12.0/24
    name: motar_motar
services:
  admin:
    container_name: admin
    depends_on:
      assets:
        condition: service_healthy
        required: true
    env_file:
      - path: motar.env
        required: true
    environment:
      ASSETS_SERVICE: $ASSETS_SERVICE
      AWS_S3_ACCESS_KEY: $MINIO_ROOT_USER
      AWS_S3_ACCESS_SECRET: $MINIO_ROOT_PASSWORD
      AWS_S3_ENDPOINT: api-minio.$BASE_URL
      CONSOLE_ACCESS_KEY: $MINIO_ROOT_USER
      CONSOLE_SECRET_KEY: $MINIO_ROOT_PASSWORD
      MINIO_ACCESS_KEY: $MINIO_ROOT_USER
      MINIO_SECRET_KEY: $MINIO_ROOT_PASSWORD
      PG_DB_CONNECTION_STRING: postgres://mot_app_user:${MOTAR_PG_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable
      PG_DB_PASSWORD: ${MOTAR_PG_PASSWORD}
      PLATFORMCONFIG.base_url: $BASE_URL
      PLATFORMCONFIG_base_url: $BASE_URL
      S3_URL: api-minio.$BASE_URL
    extra_hosts:
      - api-minio.${BASE_URL}:10.11.12.50
    image: harbor.dynepic.net/dynepic/admin:260323-main-e8124737
    networks:
      motar: null
    ports:
      - mode: ingress
        protocol: tcp
        published: "0"
        target: 8080
    restart: unless-stopped
  assets:
    container_name: assets
    depends_on:
      db-init:
        condition: service_completed_successfully
        required: true
      object-storage-init:
        condition: service_completed_successfully
        required: true
    dns:
      - ${HOST_IP}
    env_file:
      - path: motar.env
        required: true
    environment:
      AWS_S3_ACCESS_KEY: $MINIO_ROOT_USER
      AWS_S3_ACCESS_SECRET: $MINIO_ROOT_PASSWORD
      AWS_S3_ENDPOINT: api-minio.$BASE_URL
      CONSOLE_ACCESS_KEY: $MINIO_ROOT_USER
      CONSOLE_SECRET_KEY: $MINIO_ROOT_PASSWORD
      MINIO_ACCESS_KEY: $MINIO_ROOT_USER
      MINIO_SECRET_KEY: $MINIO_ROOT_PASSWORD
      NATS_CONFIG_address: $NATS_ADDRESS
      PG_DB_CONNECTION_STRING: postgres://mot_app_user:${MOTAR_PG_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable
      PG_DB_PASSWORD: ${MOTAR_PG_PASSWORD}
      PLATFORMCONFIG.base_url: $BASE_URL
      PLATFORMCONFIG_base_url: $BASE_URL
      PORT: "3000"
      S3_INTERNAL: minio:9000
      S3_URL: api-minio.$BASE_URL
      SCANNING_BUCKET: $SCANNING_BUCKET
    extra_hosts:
      - api-minio.${BASE_URL}:10.11.12.50
    healthcheck:
      interval: 5s
      retries: 15
      test:
        - CMD-SHELL
        - netstat -tulpn | grep -i node
      timeout: 5s
    image: harbor.dynepic.net/dynepic/assets:260323-main-ff6faa97
    networks:
      motar: null
    ports:
      - mode: ingress
        protocol: tcp
        published: "0"
        target: 3000
    restart: unless-stopped
  backup-util:
    container_name: backup-util
    env_file:
      - path: motar.env
        required: true
    environment:
      BACKUPTOOL_ASSETS_SERVICE: http://assets:3000
      BACKUPTOOL_DB_HOST: ${POSTGRES_HOST}
      BACKUPTOOL_DB_NAME: ${POSTGRES_DB}
      BACKUPTOOL_DB_PASSWORD: ${POSTGRES_PASSWORD}
      BACKUPTOOL_DB_PORT: ${POSTGRES_PORT}
      BACKUPTOOL_DB_USERNAME: ${POSTGRES_USER}
      BACKUPTOOL_MINIO_ACCESS_KEY: ${MINIO_ROOT_USER}
      BACKUPTOOL_MINIO_ENDPOINT: api-minio.${BASE_URL}
      BACKUPTOOL_MINIO_SECRET_KEY: ${MINIO_ROOT_PASSWORD}
      BACKUPTOOL_MINIO_SECURE: true
    extra_hosts:
      - api-minio.${BASE_URL}:10.11.12.50
    healthcheck:
      interval: 5s
      retries: 15
      test:
        - CMD-SHELL
        - curl localhost:4455/status
      timeout: 5s
    image: harbor.dynepic.net/dynepic/motar-util:0.3.5-alpha
    labels:
      - traefik.enable=false
    networks:
      motar: null
    restart: unless-stopped
  clamav:
    container_name: clamav
    environment:
      CLAMD_CONF_LocalSocket: /tmp/clamd.sock
      CLAMD_CONF_LogFile: /var/log/clamav/clamd.log
      CLAMD_CONF_StreamMaxLength: 0
      CLAMD_CONF_TCPSocket: 3310
      CLAMD_CONF_User: clamav
    extra_hosts:
      - api-minio.${BASE_URL}:10.11.12.50
    image: harbor.dynepic.net/devops/clamav:0.1.0
    networks:
      motar: null
    restart: unless-stopped
    volumes:
      - source: clamav_db
        target: /var/lib/clamav
        type: volume
        volume: {}
  db-init:
    container_name: db-init
    depends_on:
      postgres:
        condition: service_healthy
        required: true
    env_file:
      - path: motar.env
        required: true
    environment:
      MIGRATIONS_APP_USER_PASSWORD: ${MOTAR_PG_PASSWORD}
      MIGRATIONS_DB_HOST: ${POSTGRES_HOST}
      MIGRATIONS_DB_NAME: ${POSTGRES_DB}
      MIGRATIONS_DB_PASSWORD: ${POSTGRES_PASSWORD}
      MIGRATIONS_DB_PORT: ${POSTGRES_PORT}
      MIGRATIONS_DB_USERNAME: ${POSTGRES_USER}
      MIGRATIONS_DOWNLOAD_MIGRATIONS: ${POSTGRES_DOWNLOAD_BOOL}
      MIGRATIONS_GITLAB_TOKEN: ${GITLAB_TOKEN}
      MIGRATIONS_MIGRATION_VERSION: ${POSTGRES_MIGRATION_VERSION}
      S3_URL: api-minio.$BASE_URL
    healthcheck:
      interval: 10s
      retries: 5
      start_period: 10s
      test:
        - CMD-SHELL
        - /tmp/check-migration.sh
      timeout: 5s
    image: harbor.dynepic.net/dynepic/db-init:1.0.34
    labels:
      - traefik.enable=false
    networks:
      motar: null
    restart: on-failure
  devices:
    container_name: devices
    depends_on:
      assets:
        condition: service_healthy
        required: true
    env_file:
      - path: motar.env
        required: true
    environment:
      ASSETS_SERVICE: $ASSETS_SERVICE
      AWS_S3_ACCESS_KEY: $MINIO_ROOT_USER
      AWS_S3_ACCESS_SECRET: $MINIO_ROOT_PASSWORD
      AWS_S3_ENDPOINT: api-minio.$BASE_URL
      CONSOLE_ACCESS_KEY: $MINIO_ROOT_USER
      CONSOLE_SECRET_KEY: $MINIO_ROOT_PASSWORD
      MINIO_ACCESS_KEY: $MINIO_ROOT_USER
      MINIO_SECRET_KEY: $MINIO_ROOT_PASSWORD
      PG_DB_CONNECTION_STRING: postgres://mot_app_user:${MOTAR_PG_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable
      PG_DB_PASSWORD: ${MOTAR_PG_PASSWORD}
      PLATFORMCONFIG.base_url: $BASE_URL
      PLATFORMCONFIG_base_url: $BASE_URL
      S3_URL: api-minio.$BASE_URL
    extra_hosts:
      - api-minio.${BASE_URL}:10.11.12.50
    image: harbor.dynepic.net/dynepic/devices:260218-main-731c72a7
    networks:
      motar: null
    ports:
      - mode: ingress
        protocol: tcp
        published: "0"
        target: 8080
    restart: unless-stopped
  devices-permissions:
    container_name: devices-permissions
    depends_on:
      assets:
        condition: service_healthy
        required: true
      devices:
        condition: service_started
        required: true
        restart: true
    env_file:
      - path: motar.env
        required: true
    environment:
      ASSETS_SERVICE: $ASSETS_SERVICE
      AWS_S3_ACCESS_KEY: $MINIO_ROOT_USER
      AWS_S3_ACCESS_SECRET: $MINIO_ROOT_PASSWORD
      AWS_S3_ENDPOINT: api-minio.$BASE_URL
      CONSOLE_ACCESS_KEY: $MINIO_ROOT_USER
      CONSOLE_SECRET_KEY: $MINIO_ROOT_PASSWORD
      MINIO_ACCESS_KEY: $MINIO_ROOT_USER
      MINIO_SECRET_KEY: $MINIO_ROOT_PASSWORD
      PG_DB_CONNECTION_STRING: postgres://mot_app_user:${MOTAR_PG_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable
      PG_DB_PASSWORD: ${MOTAR_PG_PASSWORD}
      PLATFORMCONFIG.base_url: $BASE_URL
      PLATFORMCONFIG_base_url: $BASE_URL
      S3_URL: api-minio.$BASE_URL
      port: "8184"
    image: harbor.dynepic.net/dynepic/permissions:260323-main-778ba09b
    labels:
      - traefik.enable=false
    network_mode: service:devices
    restart: unless-stopped
  dnsmasq:
    cap_add:
      - NET_ADMIN
    container_name: dnsmasq
    env_file:
      - path: .env
        required: true
    image: harbor.dynepic.net/dynepic/dnsmasq:1.0.3
    labels:
      - traefik.udp.routers.dnsmasq.entrypoints=dns
      - traefik.udp.services.dnsmasq.loadbalancer.server.port=53
      - traefik.enable=true
    networks:
      motar:
        ipv4_address: 10.11.12.13
    ports:
      - mode: ingress
        protocol: udp
        published: "8053"
        target: 53
    restart: unless-stopped
  hub:
    container_name: hub
    depends_on:
      assets:
        condition: service_healthy
        required: true
    env_file:
      - path: motar.env
        required: true
    environment:
      ASSETS_SERVICE: $ASSETS_SERVICE
      AWS_S3_ACCESS_KEY: $MINIO_ROOT_USER
      AWS_S3_ACCESS_SECRET: $MINIO_ROOT_PASSWORD
      AWS_S3_ENDPOINT: api-minio.$BASE_URL
      CONSOLE_ACCESS_KEY: $MINIO_ROOT_USER
      CONSOLE_SECRET_KEY: $MINIO_ROOT_PASSWORD
      MINIO_ACCESS_KEY: $MINIO_ROOT_USER
      MINIO_SECRET_KEY: $MINIO_ROOT_PASSWORD
      PG_DB_CONNECTION_STRING: postgres://mot_app_user:${MOTAR_PG_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable
      PG_DB_PASSWORD: ${MOTAR_PG_PASSWORD}
      PLATFORMCONFIG.base_url: $BASE_URL
      PLATFORMCONFIG_base_url: $BASE_URL
      S3_URL: api-minio.$BASE_URL
    extra_hosts:
      - api-minio.${BASE_URL}:10.11.12.50
    image: harbor.dynepic.net/dynepic/hub:260323-main-ff6faa97
    networks:
      motar: null
    ports:
      - mode: ingress
        protocol: tcp
        published: "0"
        target: 8080
    restart: unless-stopped
  hub-permissions:
    container_name: hub-permissions
    depends_on:
      assets:
        condition: service_healthy
        required: true
      hub:
        condition: service_started
        required: true
        restart: true
    env_file:
      - path: motar.env
        required: true
    environment:
      ASSETS_SERVICE: $ASSETS_SERVICE
      AWS_S3_ACCESS_KEY: $MINIO_ROOT_USER
      AWS_S3_ACCESS_SECRET: $MINIO_ROOT_PASSWORD
      AWS_S3_ENDPOINT: api-minio.$BASE_URL
      CONSOLE_ACCESS_KEY: $MINIO_ROOT_USER
      CONSOLE_SECRET_KEY: $MINIO_ROOT_PASSWORD
      MINIO_ACCESS_KEY: $MINIO_ROOT_USER
      MINIO_SECRET_KEY: $MINIO_ROOT_PASSWORD
      PG_DB_CONNECTION_STRING: postgres://mot_app_user:${MOTAR_PG_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable
      PG_DB_PASSWORD: ${MOTAR_PG_PASSWORD}
      PLATFORMCONFIG.base_url: $BASE_URL
      PLATFORMCONFIG_base_url: $BASE_URL
      S3_URL: api-minio.$BASE_URL
      port: "8184"
    image: harbor.dynepic.net/dynepic/permissions:260323-main-778ba09b
    labels:
      - traefik.enable=false
    network_mode: service:hub
    restart: unless-stopped
  login:
    container_name: login
    depends_on:
      assets:
        condition: service_healthy
        required: true
    env_file:
      - path: motar.env
        required: true
    environment:
      ASSETS_SERVICE: $ASSETS_SERVICE
      AWS_S3_ACCESS_KEY: $MINIO_ROOT_USER
      AWS_S3_ACCESS_SECRET: $MINIO_ROOT_PASSWORD
      AWS_S3_ENDPOINT: api-minio.$BASE_URL
      CONSOLE_ACCESS_KEY: $MINIO_ROOT_USER
      CONSOLE_SECRET_KEY: $MINIO_ROOT_PASSWORD
      MINIO_ACCESS_KEY: $MINIO_ROOT_USER
      MINIO_SECRET_KEY: $MINIO_ROOT_PASSWORD
      PG_DB_CONNECTION_STRING: postgres://mot_app_user:${MOTAR_PG_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable
      PG_DB_PASSWORD: ${MOTAR_PG_PASSWORD}
      PLATFORMCONFIG.base_url: $BASE_URL
      PLATFORMCONFIG_base_url: $BASE_URL
      S3_URL: api-minio.$BASE_URL
    extra_hosts:
      - api-minio.${BASE_URL}:10.11.12.50
    image: harbor.dynepic.net/dynepic/login:260218-main-731c72a7
    networks:
      motar: null
    ports:
      - mode: ingress
        protocol: tcp
        published: "0"
        target: 8080
    restart: unless-stopped
  minio:
    command: server /data --console-address ":9001"
    container_name: minio
    env_file:
      - path: motar.env
        required: true
    environment:
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
    healthcheck:
      interval: 5s
      retries: 5
      test:
        - CMD
        - curl
        - -f
        - http://localhost:9000/minio/health/live
      timeout: 3s
    image: docker.io/minio/minio:RELEASE.2025-09-07T16-13-09Z
    labels:
      - traefik.enable=false
    networks:
      motar: null
    ports:
      - mode: ingress
        protocol: tcp
        published: "9000"
        target: 9000
      - mode: ingress
        protocol: tcp
        published: "0"
        target: 9001
    restart: unless-stopped
    volumes:
      - source: minio_data
        target: /data
        type: volume
        volume: {}
  nats:
    command:
      - -js
    container_name: nats
    extra_hosts:
      - api-minio.${BASE_URL}:10.11.12.50
    image: nats:2.11.8
    labels:
      - traefik.enable=false
    networks:
      motar: null
    restart: unless-stopped
  object-storage-init:
    container_name: obj-init
    depends_on:
      minio:
        condition: service_healthy
        required: true
    env_file:
      - path: motar.env
        required: true
    environment:
      CLEAN_BUCKET: $CLEAN_BUCKET
      INFECTED_BUCKET: $INFECTED_BUCKET
      NATS_CONFIG_address: $NATS_ADDRESS
      SCANNING_BUCKET: $SCANNING_BUCKET
      rootPassword: $MINIO_ROOT_PASSWORD
      rootUser: $MINIO_ROOT_USER
    image: harbor.dynepic.net/dynepic/obj-init:1.1.0
    labels:
      - traefik.enable=false
    networks:
      motar: null
  postgres:
    container_name: postgres
    environment:
      PGDATA: /bitnami/postgresql/data
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    healthcheck:
      interval: 5s
      retries: 5
      test:
        - CMD-SHELL
        - pg_isready -U $POSTGRES_USER -d $POSTGRES_DB
      timeout: 3s
    image: docker.io/bitnamilegacy/postgresql:17.6.0
    labels:
      - traefik.enable=false
    networks:
      motar: null
    restart: unless-stopped
    volumes:
      - source: postgres_data
        target: /bitnami/postgresql
        type: volume
        volume: {}
  profile:
    container_name: profile
    depends_on:
      assets:
        condition: service_healthy
        required: true
    env_file:
      - path: motar.env
        required: true
    environment:
      ASSETS_SERVICE: $ASSETS_SERVICE
      AWS_S3_ACCESS_KEY: $MINIO_ROOT_USER
      AWS_S3_ACCESS_SECRET: $MINIO_ROOT_PASSWORD
      AWS_S3_ENDPOINT: api-minio.$BASE_URL
      CONSOLE_ACCESS_KEY: $MINIO_ROOT_USER
      CONSOLE_SECRET_KEY: $MINIO_ROOT_PASSWORD
      MINIO_ACCESS_KEY: $MINIO_ROOT_USER
      MINIO_SECRET_KEY: $MINIO_ROOT_PASSWORD
      PG_DB_CONNECTION_STRING: postgres://mot_app_user:${MOTAR_PG_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable
      PG_DB_PASSWORD: ${MOTAR_PG_PASSWORD}
      PLATFORMCONFIG.base_url: $BASE_URL
      PLATFORMCONFIG_base_url: $BASE_URL
      S3_URL: api-minio.$BASE_URL
    extra_hosts:
      - api-minio.${BASE_URL}:10.11.12.50
    image: harbor.dynepic.net/dynepic/profile:260312-main-77cc782e
    networks:
      motar: null
    ports:
      - mode: ingress
        protocol: tcp
        published: "0"
        target: 8080
    restart: unless-stopped
  scanner:
    container_name: scanner
    depends_on:
      assets:
        condition: service_healthy
        required: true
    dns:
      - ${HOST_IP}
    environment:
      SCANNER_ALLOW_EXE_FOR: app
      SCANNER_CLAMD_ADDRESS: tcp://clamav:3310
      SCANNER_CLEAN_BUCKET: $CLEAN_BUCKET
      SCANNER_DOWNLOAD_PATH: /tmp/minio-files
      SCANNER_EVENT_NAMESPACES: motar
      SCANNER_INFECTED_BUCKET: $INFECTED_BUCKET
      SCANNER_MINIO_ACCESS_KEY: $MINIO_ROOT_USER
      SCANNER_MINIO_ENDPOINT: minio:9000
      SCANNER_MINIO_SECRET_KEY: $MINIO_ROOT_PASSWORD
      SCANNER_NATS_URL: $NATS_ADDRESS
      SCANNER_QUARANTINE_BUCKET: motar-quarantine
      SCANNER_SOURCE_BUCKET: $SCANNING_BUCKET
      SCANNER_STREAM_NAME: EVENTS
      SCANNER_SUBJECT: events.>
      SCANNER_USE_SSL: "false"
    extra_hosts:
      - api-minio.${BASE_URL}:10.11.12.50
    image: harbor.dynepic.net/dynepic/scanner:1.1.0
    labels:
      - traefik.enable=false
    networks:
      motar: null
    restart: unless-stopped
  service-checker:
    command:
      - sh
      - -c
      - scripts/check-apk.sh
    container_name: service-checker
    depends_on:
      assets:
        condition: service_healthy
        required: true
    env_file:
      - path: motar.env
        required: true
    environment:
      BASE_URL: $BASE_URL
      UPDATE_URL: ${BACKUP_ASSISTANT_URL}/motar3d/update
    extra_hosts:
      - api-minio.${BASE_URL}:10.11.12.50
    image: harbor.dynepic.net/dynepic/full-checker:0.1.2-eta
    labels:
      - traefik.enable=false
    networks:
      motar: null
    restart: "no"
  studio:
    container_name: studio
    depends_on:
      assets:
        condition: service_healthy
        required: true
    env_file:
      - path: motar.env
        required: true
    environment:
      ASSETS_SERVICE: $ASSETS_SERVICE
      AWS_S3_ACCESS_KEY: $MINIO_ROOT_USER
      AWS_S3_ACCESS_SECRET: $MINIO_ROOT_PASSWORD
      AWS_S3_ENDPOINT: api-minio.$BASE_URL
      CONSOLE_ACCESS_KEY: $MINIO_ROOT_USER
      CONSOLE_SECRET_KEY: $MINIO_ROOT_PASSWORD
      MINIO_ACCESS_KEY: $MINIO_ROOT_USER
      MINIO_SECRET_KEY: $MINIO_ROOT_PASSWORD
      PG_DB_CONNECTION_STRING: postgres://mot_app_user:${MOTAR_PG_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable
      PG_DB_PASSWORD: ${MOTAR_PG_PASSWORD}
      PLATFORMCONFIG.base_url: $BASE_URL
      PLATFORMCONFIG_base_url: $BASE_URL
      S3_URL: api-minio.$BASE_URL
    extra_hosts:
      - api-minio.${BASE_URL}:10.11.12.50
    image: harbor.dynepic.net/dynepic/studio:260323-main-df73e2ca
    networks:
      motar: null
    ports:
      - mode: ingress
        protocol: tcp
        published: "0"
        target: 8080
    restart: unless-stopped
  studio-permissions:
    container_name: studio-permissions
    depends_on:
      assets:
        condition: service_healthy
        required: true
      studio:
        condition: service_started
        required: true
        restart: true
    env_file:
      - path: motar.env
        required: true
    environment:
      ASSETS_SERVICE: $ASSETS_SERVICE
      AWS_S3_ACCESS_KEY: $MINIO_ROOT_USER
      AWS_S3_ACCESS_SECRET: $MINIO_ROOT_PASSWORD
      AWS_S3_ENDPOINT: api-minio.$BASE_URL
      CONSOLE_ACCESS_KEY: $MINIO_ROOT_USER
      CONSOLE_SECRET_KEY: $MINIO_ROOT_PASSWORD
      MINIO_ACCESS_KEY: $MINIO_ROOT_USER
      MINIO_SECRET_KEY: $MINIO_ROOT_PASSWORD
      PG_DB_CONNECTION_STRING: postgres://mot_app_user:${MOTAR_PG_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable
      PG_DB_PASSWORD: ${MOTAR_PG_PASSWORD}
      PLATFORMCONFIG.base_url: $BASE_URL
      PLATFORMCONFIG_base_url: $BASE_URL
      S3_URL: api-minio.$BASE_URL
      port: "8184"
    image: harbor.dynepic.net/dynepic/permissions:260323-main-778ba09b
    labels:
      - traefik.enable=false
    network_mode: service:studio
    restart: unless-stopped
  traefik:
    command:
      - --api.insecure=true
      - --providers.docker
      - --entrypoints.websecure.address=:443
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --providers.file.filename=/certs/traefik_dynamic.yml
      - --entrypoints.dns.address=:53/udp
    container_name: traefik
    environment:
      BASE_URL: ${BASE_URL}
    image: harbor.dynepic.net/dynepic/traefik-cert:1.1.1
    networks:
      motar:
        ipv4_address: 10.11.12.50
    ports:
      - mode: ingress
        protocol: tcp
        published: "80"
        target: 80
      - mode: ingress
        protocol: tcp
        published: "8080"
        target: 8080
      - mode: ingress
        protocol: tcp
        published: "443"
        target: 443
      - 443:443
      - 8080:8080
      - ${HOST_IP}:53:53/udp
    restart: unless-stopped
    volumes:
      - bind:
          create_host_path: true
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        type: bind
volumes:
  certs-default:
    name: motar_certs-default
  clamav_db:
    name: motar_clamav_db
  minio_data:
    driver: local
    name: motar_minio_data
  postgres_data:
    driver: local
    name: motar_postgres_data
x-common-hosts:
  extra_hosts:
    - api-minio.${BASE_URL}:10.11.12.50
